### ISSUE TITLE
Le site ne fonctionne pas quand servi sur un contextPath qui n'est pas /

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose-front#9]
Il faudrait adapter le code/le build pour gérer ce cas de figure, car on risque de vouloir servir le site en lieu et place de https://covidtracker.fr/vitemadose/

**Comment by fcamblor** [comment]
J'ai fait un fix qui permet :
- de faire un choix par défaut (*) quand on fait un `vite build`
- de permettre d'overrider ce choix par défaut avec un `vite --base /mon-context-custom/ build`

(*) Par défaut, j'ai fait en sorte que :
- La config par défaut soit `/vitemadose/`
- Sous-entendu, le jour où on veut servir sur vitemadose.covidtracker.fr, il faudra soit changer le `vite.config.ts`, soit passer un `--base /` au `vite build`

⬆️  @Floby @nicolinuxfr Est-ce que cette config par défaut vous va, ou est-ce que vous préférez l'inverse (par défaut, base=/, et on peut override à la demande avec un `--base /vitemadose/` tant que c'est nécessaire)

**Comment by fcamblor** [comment]
Une question importante, également, est de savoir si à un instant T, les 2 sites https://covidtracker.fr/vitemadose/ et https://vitemadose.covidtracker.fr devraient être effectifs en même temps (et pointer sur le site couramment buildé)

Car si c'est le cas, ça veut dire qu'il faudra déployer la même application à 2 endroits différents : l'un avec le `--base /` et l'autre avec un `--base /vitemadose/`

**Comment by Floby** [comment]
la doc dit que la valeur de `--base` par défaut c'est `'/'`.

```
  --base <path>           [string] public base path (default: /) 
```

Je propose que le script `build` dans le package dise `tsc && vite build --base ${BASE_PATH:-/}`
comme ça il mets `/` par défaut, et dans github actions ou dans un autre build il faut passer `BASE_PATH` en variable d'environnement sans toucher à la gueule de la commande
genre 

```
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.12"
      - run: npm ci
      - run: npm run build
        env: 
          BASE_URL:  "/vitemadose/"
```
